# Generated by Django 4.1 on 2022-08-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='cases',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
