# Generated by Django 4.1 on 2022-09-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_data_cases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='data',
            name='longitude',
        ),
        migrations.AddField(
            model_name='data',
            name='date_updated',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
